-- Clear all tables to start fresh with imports
TRUNCATE TABLE new_releases RESTART IDENTITY CASCADE;
TRUNCATE TABLE top_rated RESTART IDENTITY CASCADE;
TRUNCATE TABLE reviews RESTART IDENTITY CASCADE;
TRUNCATE TABLE movies_series RESTART IDENTITY CASCADE;
TRUNCATE TABLE awards RESTART IDENTITY CASCADE;
TRUNCATE TABLE movies_by_year RESTART IDENTITY CASCADE;
TRUNCATE TABLE actors RESTART IDENTITY CASCADE;
TRUNCATE TABLE mood_recommendations RESTART IDENTITY CASCADE;
TRUNCATE TABLE recommendation_pool RESTART IDENTITY CASCADE;
TRUNCATE TABLE cinema_galaxy RESTART IDENTITY CASCADE;
TRUNCATE TABLE cinema_world CASCADE;
TRUNCATE TABLE egypt_cinemas RESTART IDENTITY CASCADE;
TRUNCATE TABLE genre_frequency RESTART IDENTITY CASCADE;
TRUNCATE TABLE genre_cooccurrence RESTART IDENTITY CASCADE;
TRUNCATE TABLE point_cloud RESTART IDENTITY CASCADE;
